methodology:
  bar_type: dollar
  cv_method: purged_kfold
  embargo_pct: 0.11
  feature_neutralization: true
  labeling: triple_barrier
  n_splits: 3
metrics:
  catboost:
    accuracy: 0.5343190287294146
    auc: 0.5168383376227352
    f1: 0.4239000171402873
    precision: 0.5167033509817832
    recall: 0.5343190287294146
  ensemble:
    accuracy: 0.52878951797091
    auc: 0.50968481637669
  lightgbm:
    accuracy: 0.5350402692631326
    auc: 0.5118058949662097
    f1: 0.3953126942792215
    precision: 0.5172434117098079
    recall: 0.5350402692631326
  sharpe_analysis:
    dsr: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      AAAAAAAAAAA=
    is_significant: !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - b1
      - false
      - true
      state: !!python/tuple
      - 3
      - '|'
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      AA==
    psr: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAAAAAAAA=
    sharpe_ratio: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      Zm+M4awTKMA=
  xgboost:
    accuracy: 0.5131626397403534
    auc: 0.507465917813331
    f1: 0.505358432424381
    precision: 0.5067064922095574
    recall: 0.5131626397403534
selected_features:
- bb_upper_20
- return_5
- bb_width_10
- volume_ratio_5
symbols:
- AAPL
- ABBV
- ADBE
- AMGN
- AMZN
- AVGO
- AXP
- BA
- BAC
- BRK.B
- CAT
- COST
- CRM
- CSCO
- CVX
- DIS
- DOW
- GOOGL
- GS
- HD
- HON
- IBM
- INTC
- JNJ
- JPM
- KO
- LLY
- MA
- MCD
- META
- MMM
- MRK
- MSFT
- NKE
- NVDA
- PEP
- PG
- TMO
- TRV
- TSLA
- UNH
- V
- VZ
- WBA
- WMT
- XOM
train_size: 33274
training_date: '2025-12-13T13:32:08.855074'
val_size: 8319
